import assert from 'node:assert/strict';
export async function verify({db,password}) {
 const base='http://localhost:3000';
 const publicPage=await fetch(base).then(r=>r.text()); assert(publicPage.includes('CLASSIC BURGER')); assert(publicPage.includes('Fiyat bilgisi yakında')); assert(!publicPage.includes('yönetici panelinden'));
 assert.equal((await fetch(base+'/admin',{redirect:'manual'})).status,307);
 const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{'content-type':'application/json',origin:base},body:JSON.stringify({username:'wishfc',password})}); assert.equal(login.status,200);
 const cookie=login.headers.get('set-cookie').split(';')[0]; assert(login.headers.get('set-cookie').includes('HttpOnly')); assert(login.headers.get('set-cookie').includes('Secure'));
 const req=async(path,method,body,auth=true)=>fetch(base+path,{method,headers:{'content-type':'application/json',origin:base,...(auth?{cookie}:{})},body:body?JSON.stringify(body):undefined});
 assert.equal((await req('/api/admin/categories','POST',{name:'NO'},false)).status,401);
 const created=await req('/api/admin/categories','POST',{name:'TEST ÇĞİÖŞÜ',description:'Test',sort_order:7,is_active:true}); assert.equal(created.status,200); const {id:cat}=await created.json();
 let p={name:'TEST ÜRÜN',category_id:cat,description:'Açıklama',price:'410.50',spice_level:2,sort_order:1,is_active:true,price_options:[]};
 const cp=await req('/api/admin/products','POST',p);assert.equal(cp.status,200); const {id}=await cp.json();
 p={...p,name:'GÜNCEL ÜRÜN',description:'Yeni açıklama',price:'420.25'};
 assert.equal((await req('/api/admin/products/'+id,'PUT',p)).status,200);
 let html=await fetch(base).then(r=>r.text());assert(html.includes('GÜNCEL ÜRÜN'));assert(html.includes('420,25 TL'));
 assert.equal((await req('/api/admin/products/'+id,'PUT',{...p,price:-1})).status,400);
 assert.equal((await req('/api/admin/products/'+id,'PUT',{...p,price:true})).status,400);
 assert.equal((await req('/api/admin/products/'+id,'PUT',{...p,price:null,price_options:[{label:"5'Lİ",price:385},{label:"9'LU",price:615},{label:"12'Lİ",price:790}]})).status,200);
 assert.equal((await db.query('select count(*)::int n from product_price_options where product_id=$1',[id])).rows[0].n,3);
 await req('/api/admin/visibility','PATCH',{entity:'product',id,is_active:false});html=await fetch(base).then(r=>r.text());assert(!html.includes('GÜNCEL ÜRÜN'));assert(!html.includes('TEST ÇĞİÖŞÜ'));
 await req('/api/admin/visibility','PATCH',{entity:'product',id,is_active:true});
 await req('/api/admin/visibility','PATCH',{entity:'category',id:cat,is_active:false});html=await fetch(base).then(r=>r.text());assert(!html.includes('GÜNCEL ÜRÜN'));
 await req('/api/admin/categories/'+cat,'PUT',{name:'YENİ KATEGORİ',description:'Güncel açıklama',sort_order:0,is_active:true});
 const cats=(await db.query('select id from categories order by sort_order')).rows.map(r=>r.id);
 assert.equal((await req('/api/admin/reorder','POST',{categories:cats.reverse(),products:{[cat]:[id]}})).status,200);
 assert.equal((await db.query('select sort_order from categories where id=$1',[cat])).rows[0].sort_order,7);
 assert.equal((await req('/api/admin/products/'+id,'DELETE')).status,200);
 assert.equal((await db.query('select count(*)::int n from product_price_options where product_id=$1',[id])).rows[0].n,0);
 await req('/api/admin/categories/'+cat,'DELETE');
 const nullPrice=(await db.query("select price from products where name='WISH KOREAN CHICKEN'")).rows[0]; assert.equal(nullPrice.price,null);
 const korean=await fetch(base+'/admin/products?q=korean',{headers:{cookie}}).then(r=>r.text());assert(korean.replace(/<!--.*?-->/g,'').includes('3 sonuç'));
 const sessionCount=(await db.query('select count(*)::int n from admin_sessions')).rows[0].n;assert.equal(sessionCount,1);
 assert.equal((await req('/api/admin/logout','POST')).status,200);
 assert.equal((await req('/api/admin/categories','POST',{name:'NO'})).status,401);
 assert.equal((await db.query('select count(*)::int n from admin_sessions')).rows[0].n,0);
 for(let i=0;i<10;i++) await req('/api/admin/login','POST',{username:'invalid',password:'bad'},false);
 assert.equal((await req('/api/admin/login','POST',{username:'invalid',password:'bad'},false)).status,429);
 const exposed=(await db.query("select relname from pg_class where relname in ('categories','products','product_price_options','admin_users','admin_sessions','app_settings','admin_login_attempts') and not relrowsecurity")).rows;assert.equal(exposed.length,0);
 await db.exec("update categories set sort_order = case slug when 'burgers' then 1 when 'ekstra-soslar' then 2 when 'wings' then 3 when 'tenders' then 4 when 'wish-specials' then 5 else 6 end");
 console.log('PASS: public rendering, seed counts, null price, login, protected routes/APIs, CRUD, decimal/invalid prices, multi-price, visibility, sorting, search, logout revocation, rate limit, RLS');
}
